name = "lww_register"
version = "1.1.0"
description = "The last-write-wins register CRDT"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "lww-register-crdt" }
links = [
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
